site_name: CCMC Intro to Python

nav:
    - Home: README.md
    - Notebook basics: notebooks/Notebook_basics.ipynb
    - Python Data types: notebooks/Python_Data_Types.ipynb
    - Scientific Data Types: notebooks/Scientific_Data_Types.ipynb
    - Functions: notebooks/Functions.ipynb
    - Objects: notebooks/Custom_Types.ipynb
    - File I/O: notebooks/File_IO.ipynb
    - Executables: notebooks/Scripting.ipynb

theme: readthedocs
plugins:
    - mknotebooks:
        execute: true
markdown_extensions:
  - admonition
  - tables
  - toc:
        permalink: true